version: "3.8"

services:
  app_db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  fastapi_app:
    build: .
    image: fastapi_lesson
    ports:
      - "8000:8000"
    depends_on:
      - app_db
    environment:
      DATABASE_URL: ${DATABASE_URL}

volumes:
  pgdata:
