jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv and Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.13.3

      - name: Sync dependencies (install packages)
        run: uv sync --frozen

      - name: Run tests
        env:
          DATABASE_URL: postgresql+asyncpg://user:root@localhost:5432/app_db
          SECRET_KEY: test_secret
          ALGORITHM: HS256
          ACCESS_TOKEN_EXPIRE_MINUTES: 30
        run: uv run --frozen pytest -s -x --cov=fastapi_lesson -vv
