name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: root
          POSTGRES_DB: app_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python with uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.13'

      - name: Sync dependencies (including dev)
        run: uv sync --extra dev --frozen

      - name: Run tests with coverage
        env:
          DATABASE_URL: postgresql+asyncpg://user:root@localhost:5432/app_db
          SECRET_KEY: test_secret
          ALGORITHM: HS256
          ACCESS_TOKEN_EXPIRE_MINUTES: 30
        run: uv run --frozen pytest -s -x --cov=fastapi_lesson -vv
