name: Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: root
          POSTGRES_DB: app_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python with uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.13'

      - name: Sync dependencies (including dev)
        run: uv sync --extra dev --frozen

      - name: Export env variables from .env secret
        run: |
          echo "${{ secrets.DOTENV }}" > .env
          set -o allexport
          source .env
          set +o allexport

      - name: Run tests with coverage
        run: uv run --frozen pytest -s -x --cov=fastapi_lesson -vv
